{
 "title": "PostgreSQL Metrics",
 "time": { "from": "2018-05-22T02:26:38.648Z", "to": "2029-02-23T16:55:42.776Z" },
 "panels": [
  {
   "title": "Rows Per Second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Inserted",
     "expr": "rate(pg_stat_statements.rows_inserted::counter[1m])"
    },
    {
     "alias": "Updated",
     "expr": "rate(pg_stat_statements.rows_updated::counter[1m])"
    },
    {
     "alias": "Deleted",
     "expr": "rate(pg_stat_statements.rows_deleted::counter[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postgresql_memory_usage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postgresql_cpu_usage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(pg_stat_activity.pid)" }
   ]
  }
 ]
}